# Generated by Django 5.2.8 on 2026-02-16 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0005_fruittype_paymentgatewaysettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('commander', 'Commander'), ('admin', 'Admin')], default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='visibility',
            field=models.CharField(choices=[('unit', 'Visible to same unit'), ('vendor', 'Visible to same vendor'), ('private', 'Only creator')], default='unit', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'created_at'], name='bika_produc_vendor__1cc1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_by', 'created_at'], name='bika_produc_created_9aa6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['visibility', 'status'], name='bika_produc_visibil_eb3550_idx'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='bika.unit'),
        ),
    ]
