"""
Django settings for bika_project project.

Generated by 'django-admin startproject' using Django 5.2.8
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------------------
# Core settings
# ------------------------------------------------------------------------------
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-bika-project-secret-key-2025-change-this-in-production",
)

DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"

# Hosts
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    "10.0.2.2",          # Android emulator -> host machine
    "172.16.18.63",     # your LAN IP (example)
    "172.16.20.204",     # another LAN IP seen in your error logs
]

# Optional: allow adding extra hosts via env (comma-separated)
_extra_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", "").strip()
if _extra_hosts:
    ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(",") if h.strip()]

# ------------------------------------------------------------------------------
# Application definition
# ------------------------------------------------------------------------------
INSTALLED_APPS = [
    # Third-party apps
    "corsheaders",
    "rest_framework",

    # Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    # Local apps
    "bika.apps.BikaConfig",
]

MIDDLEWARE = [
    # CORS must come high
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ✅ Keep project package casing consistent with your folder name.
# If your project folder is actually "Bika_Project", keep these as-is.
ROOT_URLCONF = "Bika_Project.urls"
WSGI_APPLICATION = "Bika_Project.wsgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "bika.context_processors.site_info",
                "bika.context_processors.cart_details",
                "bika.context_processors.user_profile_info",
            ],
        },
    },
]

# ------------------------------------------------------------------------------
# Database
# ------------------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": os.getenv("DJANGO_DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.getenv("DJANGO_DB_NAME", str(BASE_DIR / "db.sqlite3")),
    }
}

# ------------------------------------------------------------------------------
# Password validation
# ------------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ------------------------------------------------------------------------------
# Internationalization
# ------------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "UTC")
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------------------------
# Static files
# ------------------------------------------------------------------------------
STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "bika" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# ------------------------------------------------------------------------------
# Media files
# ------------------------------------------------------------------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ------------------------------------------------------------------------------
# Default primary key field type
# ------------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------------------------------------------------------------------
# Custom authentication model
# ------------------------------------------------------------------------------
AUTH_USER_MODEL = "bika.CustomUser"

LOGIN_URL = "bika:login"
LOGIN_REDIRECT_URL = "bika:home"
LOGOUT_REDIRECT_URL = "bika:home"

# ------------------------------------------------------------------------------
# Django REST Framework + JWT (for Flutter native auth)
# ------------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # (optional) allow session auth for web pages:
        # "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("JWT_ACCESS_MINUTES", "30"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", "7"))),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ------------------------------------------------------------------------------
# CORS / CSRF
# ------------------------------------------------------------------------------
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        # "https://yourdomain.com",
        # "https://app.yourdomain.com",
    ]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://0.0.0.0:8000",
    "http://10.0.2.2:8000",
    "http://172.16.18.63:8000",
    "http://172.16.20.204:8000",
]

# ------------------------------------------------------------------------------
# Email Configuration
# ------------------------------------------------------------------------------
EMAIL_BACKEND = os.getenv("DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "your_email@example.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "your_app_password_here")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Bika <noreply@bika.com>")

# ------------------------------------------------------------------------------
# Session Configuration
# ------------------------------------------------------------------------------
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_SECURE = False if DEBUG else True
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True

# ------------------------------------------------------------------------------
# Security Settings for production
# ------------------------------------------------------------------------------
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    X_FRAME_OPTIONS = "DENY"

# ------------------------------------------------------------------------------
# Cache Configuration
# ------------------------------------------------------------------------------
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# ------------------------------------------------------------------------------
# File Upload Settings
# ------------------------------------------------------------------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# ------------------------------------------------------------------------------
# Bika Application Specific Settings
# ------------------------------------------------------------------------------
BIKA_SETTINGS = {
    "APP_NAME": "Bika",
    "APP_DESCRIPTION": "AI-Powered Fruit Quality Monitoring & E-commerce Platform",
    "APP_VERSION": "1.0.0",
    "SUPPORT_EMAIL": "support@bika.com",
    "SALES_EMAIL": "sales@bika.com",
    "ADMIN_EMAIL": "admin@bika.com",

    "MAX_PRODUCT_IMAGES": 10,
    "DEFAULT_STOCK_THRESHOLD": 5,
    "DEFAULT_TAX_RATE": 0.18,

    "SHIPPING_COST": 5000,
    "FREE_SHIPPING_THRESHOLD": 100000,
    "ORDER_PROCESSING_DAYS": 1,
    "DELIVERY_ESTIMATE_DAYS": 3,

    "DEFAULT_FRUIT_SHELF_LIFE": 7,
    "QUALITY_CHECK_INTERVAL_HOURS": 24,
    "CRITICAL_TEMP_THRESHOLD": 10,
    "CRITICAL_HUMIDITY_THRESHOLD": 95,
}

# ------------------------------------------------------------------------------
# Bika AI Settings
# ------------------------------------------------------------------------------
BIKA_AI_SERVICE_TYPE = "enhanced"
BIKA_AI_MODEL_DIR = MEDIA_ROOT / "fruit_models"
BIKA_AI_CACHE_TIMEOUT = 3600
BIKA_AI_MAX_PREDICTIONS_PER_BATCH = 1000

# ------------------------------------------------------------------------------
# Create required directories
# ------------------------------------------------------------------------------
required_dirs = [
    MEDIA_ROOT,
    MEDIA_ROOT / "products",
    MEDIA_ROOT / "categories",
    MEDIA_ROOT / "profiles",
    MEDIA_ROOT / "business_logos",
    MEDIA_ROOT / "trained_models",
    MEDIA_ROOT / "datasets",
    MEDIA_ROOT / "fruit_datasets",
    MEDIA_ROOT / "fruit_models",
    MEDIA_ROOT / "services",
    MEDIA_ROOT / "testimonials",
    MEDIA_ROOT / "fruits",
    MEDIA_ROOT / "site" / "logo",
    MEDIA_ROOT / "site" / "favicon",
    STATIC_ROOT,
    BASE_DIR / "logs",
]

for directory in required_dirs:
    directory.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------------------------
# Optional apps (add only if installed)
# ------------------------------------------------------------------------------
try:
    import crispy_forms  # noqa: F401
    INSTALLED_APPS.insert(0, "crispy_forms")
    CRISPY_TEMPLATE_PACK = "bootstrap4"
except ImportError:
    pass

try:
    import django_extensions  # noqa: F401
    INSTALLED_APPS.append("django_extensions")
except ImportError:
    pass

try:
    import mathfilters  # noqa: F401
    INSTALLED_APPS.append("mathfilters")
except ImportError:
    pass
